name: Create Release

on:
  push:
    tags:
      - 'v*'  # 以 'v' 开头的标签触发

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 创建 Release 和上传源码包
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
